services:

  merchant-service:
    depends_on:
      aws-mock:
        condition: service_healthy
      acquirer-ngenius-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    extends:
      service: merchant-service
      file: docker-compose.yml

  notification-service:
    depends_on:
      aws-mock:
        condition: service_healthy
    extends:
      service: notification-service
      file: docker-compose.yml

  acquirer-ngenius-service:
    depends_on:
      mock-acquirer-ngenius-service:
        condition: service_healthy
    extends:
      service: acquirer-ngenius-service
      file: docker-compose.yml

  mock-acquirer-ngenius-service:
    extends:
      service: mock-acquirer-ngenius-service
      file: docker-compose.yml
    environment:
      - MOCK_NGENIUS_CLIENT_URL=http://mock-acquirer-ngenius-service

  portal-service:
    depends_on:
      aws-mock:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    extends:
      service: portal-service
      file: docker-compose.yml

  opensearch:
    extends:
      service: opensearch
      file: docker-compose.yml

  aws-mock:
    extends:
      service: aws-mock
      file: docker-compose.yml

  api-test:
    image: npgw/api-test:latest
    container_name: api-test
    depends_on:
      merchant-service:
        condition: service_healthy
      portal-service:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: docker/image-api-test/Dockerfile
    env_file:
      ee.env
