name: Generate and deploy the docs to Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g openapi-merge-cli

      - run: echo "PyYAML==5.4.1" > requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install pyyaml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: curl https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.7.0/openapi-generator-cli-7.7.0.jar -o openapi-generator-cli.jar

      - name: Create Merchant Spec (Docs)
        run: python3 ./rest/script/yaml-merge.py ./rest/processing/part-doc-api.yaml ./api-merchant.yaml /info > ./api-merchant-doc.yaml

      - name: Create Merchant Docs
        run: |
          rm -rf docs
          java -jar openapi-generator-cli.jar generate -i api-merchant-doc.yaml -g html2 -o docs

      - name: Delete discriminator (AWS doesn't support)
        run: |
          sed '/discriminator/,/CreditCard: CreditCardDetails/d' api-merchant.yaml > prepared-api-merchant.yaml

      - name: Create Merchant Spec (API)
        run: openapi-merge-cli --config ./rest/processing/merge-config.json

      - name: Create Merchant Spec (AWS)
        run: python3 ./rest/script/yaml-merge.py ./rest/processing/part-aws-api.yaml ./api-merchant-processing.yaml x-amazon- > ./docs/merchant-v1.yaml

      - name: Validation Merchant Spec (AWS)
        run: java -jar openapi-generator-cli.jar validate -i ./docs/merchant-v1.yaml --recommend

      - name: Create Portal Spec (API)
        run: java -jar openapi-generator-cli.jar generate -i ./rest/api-portal.yaml -g openapi-yaml -o ./temp --additional-properties outputFile=./api-portal-merchant.yaml

      - name: Delete discriminator (AWS doesn't support)
        run: |
          sed '/discriminator/,/propertyName: paymentMethod/d' ./temp/api-portal-merchant.yaml > ./temp/prepared-api-portal-merchant.yaml

      - name: Refactor Portal Spec (AWS)
        run: sed 's|BaseTransaction_allOf_paymentDetails|BaseTransactionPaymentDetails|g' ./temp/prepared-api-portal-merchant.yaml > ./api-portal-merchant.yaml

      - name: Create Portal Spec (AWS)
        run: python3 ./rest/script/yaml-merge.py ./rest/portal/part-aws-api.yaml ./api-portal-merchant.yaml x-amazon- > ./docs/portal-v1.yaml

      - name: Validation Portal Spec (AWS)
        run: java -jar openapi-generator-cli.jar validate -i ./docs/portal-v1.yaml --recommend

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
